apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tetris
  name: tetris
  namespace: abastidasc-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: ['sh', '-c', 'mkdir -p /var/cache/nginx/client_temp && chown -R 1000:1000 /var/cache/nginx']
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
      containers:
        - name: tetris
          image: adijaiswal/tetris:v1
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000 # Usuario no root
            runAsGroup: 1000
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
      volumes:
        - name: nginx-cache
          emptyDir: {}
