
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-deployment
  namespace: abastidasc-devops
spec:
  replicas: 2 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
        - name: tetris
          image: adijaiswal/tetris:v1 # Replace with the actual image tag
          command: ["sh", "-c", "chown -R nginx:nginx /var/cache/nginx"]
          securityContext:
            privileged: true
          ports:
            - containerPort: 80 # Replace with the port your Tetris game listens on
      
