apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
  namespace: abastidasc-devops
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
        - name: tetris
          image: adijaiswal/tetris:v2 
          ports:
            - containerPort: 80 
