
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tetris
  name: tetris
  namespace: abastidasc-devops
spec:
  securityContext:
    runAsUser: 1000
  replicas: 2 
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
        - name: tetris
          image: adijaiswal/tetris:v1
          imagePullPolicy: IfNotPresent
          allowPrivilegeEscalation: true
