apiVersion: v1
kind: Service
metadata:
  name: tetris
  namespace: abastidasc-devops
  labels:
    app: tetris
spec:
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  selector:
    app: tetris
