apiVersion: v1
kind: Service
metadata:
  name: tetris
  namespace: abastidasc-devops
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    app: tetris
