apiVersion: v1
kind: Service
metadata:
  name: tetris
  namespace: abastidasc-devops
  labels:
    app: tetris
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  selector:
    app: tetris
