apiVersion: v1
kind: Service
metadata:
  name: tetris
  namespace: abastidasc-devops
spec:
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP
  selector:
    app: tetris
