apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: ekart
  name: shopping-cart
  namespace: abastidasc-devops
spec:
  selector:
    matchLabels:
      app: shopping-cart
  replicas: 2 
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
        - name: shopping-cart
          image: adijaiswal/shopping-cart:latest
          imagePullPolicy: IfNotPresent
          ports:
          
      
