apiVersion: apps/v1
kind: Deployment 
metadata:
  name: shopping-cart
spec:
  selector:
    matchLabels:
      app: shopping-cart
  replicas: 2 
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
        - name: shopping-cart
          image: adijaiswal/shopping-cart:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090 # The port that the container is running on in the cluster
          
      
