apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: shopping-cart
  name: shopping-cart
  namespace: abastidasc-devops
spec:
  port:
    targetPort: 8070
  to:
    kind: Service
    name: shopping-cart
    weight: 100
