---
apiVersion: v1
kind: Service
metadata:
  name: shopping-cart
  namespace: abastidasc-devops
  labels:
    app: shopping-cart
spec:
  ports:
    - protocol: "TCP"
      port: 8070
      targetPort: 8070
      type: LoadBalancer # type of the service.
  selector:
    app: shopping-cart
